/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan4;

/**
 *
 * @author Prdigma
 */
public class part2 extends javax.swing.JFrame {

    /**
     * Creates new form part2
     */
    public part2(String nama, String absen, String kelas, String alamat) {
        initComponents();
        idnm.setText(nama);
        idabsn.setText(absen);
        idkls.setText(kelas);
        idalmt.setText(alamat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idkls = new javax.swing.JLabel();
        idnm = new javax.swing.JLabel();
        idalmt = new javax.swing.JLabel();
        idabsn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Hasil Biodata");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 70, 20);

        idkls.setText("Hasil 3 :");
        getContentPane().add(idkls);
        idkls.setBounds(70, 140, 180, 20);

        idnm.setText("Hasil 1 :");
        getContentPane().add(idnm);
        idnm.setBounds(70, 80, 190, 20);

        idalmt.setText("Hasil 4 :");
        getContentPane().add(idalmt);
        idalmt.setBounds(70, 170, 160, 20);

        idabsn.setText("Hasil 2 :");
        getContentPane().add(idabsn);
        idabsn.setBounds(70, 110, 170, 20);

        setBounds(0, 0, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(part2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(part2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(part2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(part2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new part1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idabsn;
    private javax.swing.JLabel idalmt;
    private javax.swing.JLabel idkls;
    private javax.swing.JLabel idnm;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
